### ISSUE TITLE
Handling SYSCALL return values?

### ISSUE THREAD

**Issue by Naville** [jsherman212/svc_stalker#1]
Hey:
Given current structure it seems like this project doesn't support hijacking or merely logging return values from the kernel side? Say I was about to hijack ``open()``, I don't think I can obtain the returned file descriptor?

**Comment by jsherman212** [comment]
Correct, currently this project only supports intercepting calls before they happen. Support for intercepting calls after they're completed but before the process which made the call sees the return value is planned. (school has started up again so I have less time to dedicate to that, but again, it's definitely planned)

**Comment by Naville** [comment]
FYI it's not broken, check https://github.com/checkra1n/BugTracker/issues/1744 they just changed the ABI and API

**Comment by Naville** [comment]
(on iOS14)

**Comment by Naville** [comment]
After fixing Checkra1n 0.11 support, I got an error about failed to find sysent. Previously that part was working perfectly fine on my OS at commit 477b345

**Comment by jsherman212** [comment]
Oh, I must have missed the ABI/API changes. Weird. You got failed to find sysent on ios 14 or 13 with checkrain 11? If it was 14, the patchfinder isn't updated for that because I was working under the assumption that it _was_ broken :p I will get on that, shouldn't be that bad to update. I should probably start pulling 14 kernels tonight ;_;

**Comment by Naville** [comment]
I actually forgot, got way too much devices at hand and already lost track of which device I used. Nonetheless I'm more interested in how did you symbolicate the kernel to write the pathfinders

**Comment by jsherman212** [comment]
It would be really valuable for me to know if it failed on 13 or 14 and the checkrain version you used😅 If it failed on 14, that's expected, but if it failed on 13 I need to fix the patchfinder before I start doing iOS 14/checkrain 0.11 support.

for your question, I only patch kernel, not kexts, so I use the XNU source to aid in reversing. Xrefing "Invalid SVC_64 context" gives me sleh_synchronous, and sleh_synchronous gives me mach_syscall, unix_syscall, exception_triage, platform_syscall, and a few others.

**Comment by Naville** [comment]
Cheers! Probably iOS 14 though since I recompiled my local code today and tested it again in my iOS 13, it worked as intended

**Comment by jsherman212** [comment]
Cool
