### ISSUE TITLE
Fatal error on 14.3

### ISSUE THREAD

**Issue by 0x3c3e** [jsherman212/svc_stalker#3]
Hi,

The svc_stalker worked on 14.2, but on 14.3 it throws fatal error during boot process.
svc_stalker on latest commit 1c5b69261d9f3f530c820bccd253d3e985ad6e77
Env: 6S on 14.3, checkra1n 0.12.1
![photo_2020-12-17_00-18-45](https://user-images.githubusercontent.com/17056564/102407730-9d1aff00-3ffd-11eb-8914-27eaae0a0477.jpg)

Check location: https://github.com/jsherman212/svc_stalker/blob/1c5b69261d9f3f530c820bccd253d3e985ad6e77/module/pf/ss_patcher.c#L313-L315

**Comment by jsherman212** [comment]
Yeah, I should probably update the patchfinders for 14.3. Will get on that today (or tomorrow, given how long it takes to pull 14.3 kernels/update the phone I use to test this project)

**Comment by jsherman212** [comment]
That didn't take as long as I thought it would. Could you clone the latest commit to the develop branch, try again, and report  back? @0x3c3e

`git clone https://github.com/jsherman212/svc_stalker.git -b develop`

Thanks

**Comment by 0x3c3e** [comment]
I think it's fixed, at least there is no fatal error now.

Thanks.

**Comment by jsherman212** [comment]
cool, mini_strace works as well?
